const $ = (s) => document.querySelector(s); const $$=(s)=>[...document.querySelectorAll(s)];
const esc=(v)=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const row=(a,b)=>`<div class="row"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`;
async function get(path){const r=await fetch(path);if(!r.ok)throw new Error(`${r.status}`);return r.json()}
function table(items,cols,clickable){if(!items?.length)return 'No records yet.';return `<table><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${items.map(x=>`<tr>${cols.map((c,i)=>`<td class="${clickable&&i===0?'link':''}" ${clickable&&i===0?`data-trade="${esc(x[c])}"`:''}>${esc(x[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
async function refresh(){try{const [s,p,b,r,pos,l,m,o,t,sys]=await Promise.all([get('/api/v1/status'),get('/api/v1/performance'),get('/api/v1/brain?limit=1'),get('/api/v1/risk'),get('/api/v1/positions'),get('/api/v1/learning'),get('/api/v1/market?limit=50'),get('/api/v1/opportunities?limit=50'),get('/api/v1/trades?limit=50'),get('/api/v1/system')]);
$('#mode').textContent=s.mode;$('#gate').textContent=`Entries ${s.new_entries_paused?'PAUSED':'enabled'} · Emergency ${s.emergency_stop?'ON':'off'} · Reconciliation ${s.reconciliation_ok?'OK':'BLOCKED'}`;
$('#metrics').innerHTML=[['Closed trades',p.closed_trades],['Expectancy R',Number(p.expectancy_r||0).toFixed(3)],['Net P/L',Number(p.net_pnl||0).toFixed(2)],['Win rate',`${(100*(p.win_rate||0)).toFixed(1)}%`]].map(x=>`<div class="metric"><label>${x[0]}</label><strong>${x[1]}</strong></div>`).join('');
const n=b.items?.[0];$('#brain').innerHTML=n?row('Direction',n.direction)+row('BUY',Number(n.buy_score).toFixed(3))+row('SELL',Number(n.sell_score).toFixed(3))+row('HOLD',Number(n.hold_score).toFixed(3))+row('Brainflow',Number(n.brainflow_score).toFixed(3)):'No inference recorded yet.';
$('#risk').innerHTML=(r.decision_counts||[]).slice(0,8).map(x=>row(`${x.risk_decision}${x.rejection_reason?' · '+x.rejection_reason:''}`,x.count)).join('')||'No decisions.';$('#positions').innerHTML=(pos.items||[]).slice(0,8).map(x=>row(x.trade_id,x.actual_entry)).join('')||'No open positions.';
const champ=(l.artifacts||[]).find(x=>x.role==='CHAMPION'),chall=(l.artifacts||[]).find(x=>x.role==='CHALLENGER');$('#learningSummary').innerHTML=row('Champion',champ?.artifact_id)+row('Challenger',chall?.artifact_id);$('#marketTable').innerHTML=table(m.items,['symbol','broker_symbol','observed_at_utc','feature_version','dataset_version']);$('#opportunityTable').innerHTML=table(o.items,['opportunity_id','decided_at_utc','direction','brainflow_score','confidence','risk_decision','rejection_reason']);$('#tradeTable').innerHTML=table(t.items,['trade_id','opened_at_utc','closed_at_utc','actual_entry','exit_price','realized_r','net_pnl'],true);$('#learningTable').innerHTML=table(l.artifacts,['artifact_id','role','network_version','feature_version','scaler_version','dataset_version','created_at_utc','promoted_at_utc']);$('#systemInfo').innerHTML=row('API',sys.api_version)+row('Dashboard',sys.dashboard_version)+row('Database',sys.database_available?'available':'not available')+row('Warnings',(sys.warnings||[]).join(', ')||'none');$('#configInfo').textContent=JSON.stringify(sys.config,null,2);$('#connection').textContent='API online';$$('[data-trade]').forEach(el=>el.onclick=()=>loadReplay(el.dataset.trade));}catch(e){$('#connection').textContent='API unavailable'}}
async function loadReplay(id){try{$('#replay').textContent=JSON.stringify(await get(`/api/v1/trades/${encodeURIComponent(id)}/replay`),null,2)}catch(e){$('#replay').textContent=`Replay unavailable: ${e.message}`}}
$$('[data-view]').forEach(btn=>btn.onclick=()=>{$$('[data-page]').forEach(p=>p.hidden=p.dataset.page!==btn.dataset.view)});$$('[data-command]').forEach(btn=>btn.onclick=async()=>{try{const r=await fetch('/api/v1/commands',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command:btn.dataset.command})});if(!r.ok)throw new Error(await r.text());await refresh()}catch(e){alert(`Command rejected: ${e.message}`)}});
function connectEvents(){const proto=location.protocol==='https:'?'wss':'ws',ws=new WebSocket(`${proto}://${location.host}/ws/v1/events`);ws.onopen=()=>$('#connection').textContent='Live stream online';ws.onmessage=e=>{const x=JSON.parse(e.data),d=document.createElement('div');d.className='event';d.innerHTML=`<b>${esc(x.event_type)}</b> ${esc(x.occurred_at_utc)} · ${esc(x.source)}`;$('#events').prepend(d);while($('#events').children.length>100)$('#events').lastChild.remove()};ws.onclose=()=>setTimeout(connectEvents,1500)}
refresh();setInterval(refresh,5000);connectEvents();
